"""
PyTorch implementation of the Gibbs SeaWater (GSW) Oceanographic Toolbox.

This is a PyTorch-based reimplementation of the GSW Python package,
providing numerical parity with the reference numpy implementation
and support for automatic differentiation via PyTorch's autograd.

Extensive documentation is available from https://www.teos-10.org/;
users of this Python package are strongly encouraged to study the
documents posted there.

This implementation maintains the same API as the original GSW-Python
package, but uses PyTorch tensors instead of numpy arrays, enabling
GPU acceleration and automatic differentiation.

Key differences from numpy GSW:
- Functions accept and return torch.Tensor objects
- Numpy arrays are automatically converted to tensors
- All operations support automatic differentiation
- GPU acceleration is available when using CUDA tensors
- Scalar returns are 0-dimensional tensors (use .item() to get Python scalars)
"""

from . import conversions, density, energy, geostrophy, ice, stability, utility
from .conversions import (
    SAAR,
    C_from_SP,
    CT_first_derivatives,
    CT_from_enthalpy,
    CT_from_entropy,
    CT_from_pt,
    CT_from_rho,
    CT_from_t,
    CT_maxdensity,
    CT_second_derivatives,
    SA_from_rho,
    SA_from_SP,
    SA_from_Sstar,
    SP_from_C,
    SP_from_SA,
    SP_from_SK,
    SP_from_SR,
    SP_from_Sstar,
    SR_from_SP,
    Sstar_from_SA,
    Sstar_from_SP,
    adiabatic_lapse_rate_from_CT,
    deltaSA_from_SP,
    entropy_first_derivatives,
    entropy_from_CT,
    entropy_from_pt,
    entropy_from_t,
    entropy_second_derivatives,
    grav,
    p_from_z,
    pt0_from_t,
    pt_first_derivatives,
    pt_from_CT,
    pt_from_entropy,
    pt_from_t,
    pt_second_derivatives,
    t90_from_t68,
    t_from_CT,
    z_from_p,
)
from .density import (
    alpha,
    alpha_on_beta,
    beta,
    infunnel,
    kappa,
    pot_rho_t_exact,
    rho,
    rho_alpha_beta,
    rho_first_derivatives,
    rho_first_derivatives_wrt_enthalpy,
    rho_second_derivatives,
    rho_second_derivatives_wrt_enthalpy,
    rho_t_exact,
    sigma0,
    sigma1,
    sigma2,
    sigma3,
    sigma4,
    sound_speed,
    specvol,
    specvol_alpha_beta,
    specvol_anom_standard,
    specvol_first_derivatives,
    specvol_first_derivatives_wrt_enthalpy,
    specvol_second_derivatives,
    specvol_second_derivatives_wrt_enthalpy,
    specvol_t_exact,
    spiciness0,
    spiciness1,
    spiciness2,
)
from .energy import (
    dynamic_enthalpy,
    enthalpy,
    enthalpy_diff,
    enthalpy_first_derivatives,
    enthalpy_second_derivatives,
    enthalpy_SSO_0,
    enthalpy_t_exact,
    internal_energy,
    latentheat_evap_CT,
    latentheat_evap_t,
    latentheat_melting,
)
from .freezing import CT_freezing, SA_freezing_from_CT, pressure_freezing_CT, t_freezing
from .geostrophy import distance, f, geostrophic_velocity, unwrap  # noqa
from .ice import (
    adiabatic_lapse_rate_ice,
    alpha_wrt_t_ice,
    chem_potential_water_ice,
    cp_ice,
    enthalpy_ice,
    entropy_ice,
    ice_fraction_to_freeze_seawater,
    internal_energy_ice,
    kappa_const_t_ice,
    kappa_ice,
    melting_ice_equilibrium_SA_CT_ratio,
    melting_ice_into_seawater,
    melting_ice_SA_CT_ratio,
    melting_seaice_into_seawater,
    melting_seaice_SA_CT_ratio,
    pot_enthalpy_ice_freezing,
    pressure_coefficient_ice,
    seaice_fraction_to_freeze_seawater,
)
from .interpolation import sa_ct_interp, tracer_ct_interp  # noqa
from .stability import (  # noqa
    IPV_vs_fNsquared_ratio,
    Nsquared,
    Turner_Rsubrho,
    cabbeling,
    thermobaric,
)
from .utility import (  # noqa
    O2sol,
    O2sol_SP_pt,
    chem_potential_water_t_exact,
    pchip_interp,
    t_deriv_chem_potential_water_t_exact,
)

try:
    from ._version import __version__
except ImportError:
    __version__ = "unknown"

__all__ = [
    "conversions",
    "density",
    "energy",
    "geostrophy",
    "ice",
    "stability",
    "utility",
    "t90_from_t68",
    "grav",
    "p_from_z",
    "z_from_p",
    "CT_from_t",
    "CT_from_pt",
    "CT_from_enthalpy",
    "CT_from_entropy",
    "CT_from_rho",
    "CT_maxdensity",
    "SAAR",
    "deltaSA_from_SP",
    "SA_from_SP",
    "SA_from_Sstar",
    "SP_from_SA",
    "SP_from_SK",
    "SP_from_SR",
    "SP_from_Sstar",
    "SR_from_SP",
    "Sstar_from_SA",
    "Sstar_from_SP",
    "C_from_SP",
    "SP_from_C",
    "t_from_CT",
    "pt_from_CT",
    "pt_from_t",
    "pt_from_entropy",
    "pt0_from_t",
    "entropy_from_CT",
    "entropy_from_pt",
    "entropy_from_t",
    "entropy_first_derivatives",
    "entropy_second_derivatives",
    "adiabatic_lapse_rate_from_CT",
    "SA_from_rho",
    "CT_first_derivatives",
    "CT_second_derivatives",
    "pt_first_derivatives",
    "pt_second_derivatives",
    "specvol_alpha_beta",
    "dynamic_enthalpy",
    "enthalpy",
    "enthalpy_diff",
    "enthalpy_first_derivatives",
    "enthalpy_second_derivatives",
    "enthalpy_SSO_0",
    "enthalpy_t_exact",
    "internal_energy",
    "latentheat_evap_CT",
    "latentheat_evap_t",
    "latentheat_melting",
    "CT_freezing",
    "CT_freezing_first_derivatives",
    "CT_freezing_poly",
    "t_freezing",
    "t_freezing_first_derivatives",
    "SA_freezing_from_CT",
    "SA_freezing_from_t",
    "pressure_freezing_CT",
    "enthalpy_ice",
    "entropy_ice",
    "internal_energy_ice",
    "cp_ice",
    "adiabatic_lapse_rate_ice",
    "ice_fraction_to_freeze_seawater",
    "melting_ice_equilibrium_SA_CT_ratio",
    "melting_ice_into_seawater",
    "melting_ice_SA_CT_ratio",
    "melting_seaice_into_seawater",
    "melting_seaice_SA_CT_ratio",
    "pot_enthalpy_ice_freezing",
    "seaice_fraction_to_freeze_seawater",
    "alpha_wrt_t_ice",
    "chem_potential_water_ice",
    "kappa_const_t_ice",
    "kappa_ice",
    "pressure_coefficient_ice",
    "Nsquared",
    "Turner_Rsubrho",
    "IPV_vs_fNsquared_ratio",
    "thermobaric",
    "cabbeling",
    "rho",
    "rho_first_derivatives",
    "rho_first_derivatives_wrt_enthalpy",
    "rho_second_derivatives",
    "rho_second_derivatives_wrt_enthalpy",
    "rho_t_exact",
    "specvol_first_derivatives",
    "specvol_first_derivatives_wrt_enthalpy",
    "specvol_second_derivatives",
    "specvol_second_derivatives_wrt_enthalpy",
    "specvol_t_exact",
    "pot_rho_t_exact",
    "spiciness0",
    "spiciness1",
    "spiciness2",
    "infunnel",
    "kappa",
    "sound_speed",
    "alpha",
    "beta",
    "specvol",
    "specvol_anom_standard",
    "rho_alpha_beta",
    "alpha_on_beta",
    "sigma0",
    "sigma1",
    "sigma2",
    "sigma3",
    "sigma4",
    "latentheat_evap_CT",
    "latentheat_evap_t",
    "latentheat_melting",
    "distance",
    "f",
    "geostrophic_velocity",
    "O2sol",
    "O2sol_SP_pt",
    "unwrap",
    "sa_ct_interp",
    "tracer_ct_interp",
    "pchip_interp",
]
